//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THavelook
    {
        public THavelook()
        {
            this.THaveLook_image = new HashSet<THaveLook_image>();
        }
    
        public long ID { get; set; }
        public string TopName { get; set; }
        public System.DateTime Addtime { get; set; }
        public int Items_ID { get; set; }
        public string TextValue { get; set; }
        public string Personname { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> del { get; set; }
    
        public virtual T_City T_City { get; set; }
        public virtual T_Items T_Items { get; set; }
        public virtual ICollection<THaveLook_image> THaveLook_image { get; set; }
    }
}
